version: '{build}'
# clone_folder: c:\projects\sgrid

image: Visual Studio 2019

init:
  - ps: ($env:APPVEYOR_SAVE_CACHE_ON_ERROR = "true")


# cache dependencies libraries.
cache:



install:
# Install MS-MPI
- ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe'
- msmpisetup.exe -unattend
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%

# Install MS-MPI SDK
- ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi'
- msmpisdk.msi /quiet /passive
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%


# Install Blas/Lapack
- ps: Start-FileDownload 'http://netlib.org/lapack/lapack.tgz'
- 7z x lapack.tgz -so | 7z x -si -ttar > nul
- cd lapack\lapack-3.10.1
- IF NOT EXIST C:\projects\installations\lapack cmake -G "Visual Studio 16 2019" -A x64 -S . -B "build" -DCMAKE_INSTALL_PREFIX="C:\projects\installations\lapack" -DCMAKE_CXX_FLAGS="/W0 /EHsc" && cmake --build build --config Release --target install

#Install Petsc




