#ifndef UTOPIA_VERSION_HPP
#define UTOPIA_VERSION_HPP

#define UTOPIA_VERSION_MAJOR 0
#define UTOPIA_VERSION_MINOR 1
#define UTOPIA_VERSION_PATCH 0
#define UTOPIA_GIT_VERSION ""
//#define UTOPIA_VERSION_TWEAK 
#define UTOPIA_VERSION "0.1.0"

#endif
