
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was UtopiaConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

if (NOT CMAKE_CXX_EXTENSIONS)
    # set extensionst to OFF if not specified explicitly
    set(CMAKE_CXX_EXTENSIONS OFF)
endif()

include(CMakeFindDependencyMacro)
if ()
    find_dependency(Trilinos HINTS Trilinos_DIR-NOTFOUND)
endif()

########## old style variables. Preferably you should use target_link_libraries(my_target Utopia::utopia) ################
#Automatically generated by utopia CMakeLists.txt


LIST(APPEND UTOPIA_INCLUDES
	/usr/local/include
	"/opt/petsc/include"
 
)


LIST(APPEND UTOPIA_LIBRARIES
	-L/usr/local/lib
	-lutopia 

	"/opt/petsc/lib/libpetsc.so"
	"/opt/petsc/lib/libcmumps.a"
	"/opt/petsc/lib/libdmumps.a"
	"/opt/petsc/lib/libsmumps.a"
	"/opt/petsc/lib/libzmumps.a"
	"/opt/petsc/lib/libmumps_common.a"
	"/opt/petsc/lib/libpord.a"
	"/opt/petsc/lib/libscalapack.a"
	"/opt/petsc/lib/libsuperlu_dist.so"
	"/opt/petsc/lib/libHYPRE.a"
	"/usr/lib/liblapack.so"
	"/usr/lib/libblas.so"
	"/opt/petsc/lib/libparmetis.so"
	"/opt/petsc/lib/libmetis.so"
	"/opt/petsc/lib/libmpifort.so"
	"/opt/petsc/lib/libmpi.so"
	"/usr/lib/libgfortran.so"
	"/usr/lib/libm.a"
	"/usr/lib/libssp_nonshared.a"
	"/usr/lib/libgcc_s.so"
	"/usr/lib/libquadmath.so"
	"/usr/lib/libstdc++.so"
	"/usr/lib/libdl.a"
 )


LIST(APPEND UTOPIA_DEFS
	"-DLAPACK_USE_F2C"
 
)


LIST(APPEND UTOPIA_CXX_FLAGS
	" -Wall -Werror=enum-compare -Werror=delete-non-virtual-dtor -Werror=reorder -Werror=return-type -Wextra  -Wall -Werror=enum-compare -Werror=delete-non-virtual-dtor -Werror=reorder -Werror=return-type -Wextra  -Wall -Werror=enum-compare -Werror=delete-non-virtual-dtor -Werror=reorder -Werror=return-type -Wextra "
 
)


LIST(APPEND UTOPIA_C_COMPILER
	"/usr/bin/clang"
 
)


LIST(APPEND UTOPIA_CXX_COMPILER
	"/usr/bin/clang++"
 
)


########## end of old style variables ####################################################################################

include("${CMAKE_CURRENT_LIST_DIR}/UtopiaTargets.cmake")

