#Automatically generated by utopia CMakeLists.txt

UTOPIA_INCLUDES=-I/usr/local/include -I/opt/petsc/include  
UTOPIA_LIBRARIES=-L/usr/local/lib   -lutopia /opt/petsc/lib/libpetsc.so /opt/petsc/lib/libcmumps.a /opt/petsc/lib/libdmumps.a /opt/petsc/lib/libsmumps.a /opt/petsc/lib/libzmumps.a /opt/petsc/lib/libmumps_common.a /opt/petsc/lib/libpord.a /opt/petsc/lib/libscalapack.a /opt/petsc/lib/libsuperlu_dist.so /opt/petsc/lib/libHYPRE.a /usr/lib/liblapack.so /usr/lib/libblas.so /opt/petsc/lib/libparmetis.so /opt/petsc/lib/libmetis.so /opt/petsc/lib/libmpifort.so /opt/petsc/lib/libmpi.so /usr/lib/libgfortran.so /usr/lib/libm.a /usr/lib/libssp_nonshared.a /usr/lib/libgcc_s.so /usr/lib/libquadmath.so /usr/lib/libstdc++.so /usr/lib/libdl.a  
UTOPIA_DEFS=-DLAPACK_USE_F2C  
UTOPIA_CXX_FLAGS= -Wall -Werror=enum-compare -Werror=delete-non-virtual-dtor -Werror=reorder -Werror=return-type -Wextra  -Wall -Werror=enum-compare -Werror=delete-non-virtual-dtor -Werror=reorder -Werror=return-type -Wextra  -Wall -Werror=enum-compare -Werror=delete-non-virtual-dtor -Werror=reorder -Werror=return-type -Wextra 
UTOPIA_CXX_COMPILER=/usr/bin/clang++
UTOPIA_C_COMPILER=/usr/bin/clang
