version: '{build}'
clone_folder: c:\projects\utopia

image: Visual Studio 2019

init:
  - ps: ($env:APPVEYOR_SAVE_CACHE_ON_ERROR = "true")


# cache dependencies libraries.
cache:



install:
# Install MS-MPI
- ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe'
- msmpisetup.exe -unattend
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%

# Install MS-MPI SDK
- ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi'
- msmpisdk.msi /quiet /passive
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%


# Install Blas/Lapack
# - ps: Start-FileDownload 'http://netlib.org/lapack/lapack.tgz'
# - 7z x lapack.tgz -so | 7z x -si -ttar > nul
# - cd lapack-3.10.
# - IF NOT EXIST C:\projects\installations\lapack cmake -G "MinGW Makefiles" . -B "build" -DCMAKE_INSTALL_PREFIX="C:\projects\installations\lapack" -DCMAKE_CXX_FLAGS="/W0 /EHsc" && cmake --build build --config Release --target install


# Other way with ninja
# - cmake -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX="C:\projects\installations\lapack" -DCMAKE_C_COMPILER:FILEPATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENTIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\projects\lapack-3.10.1"

#Install Petsc
# Does not natively compile with windows
# Cannot use MS-MPI, Intel-MPI, MPICH2
# Options are, Cygwin to compile, MSYS, 
# - ps: Start-FileDownload 'https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.18.3.tar.gz'
# - 7z x petsc-3.18.3.tar.gz -so | 7z x -si -ttar > nul
# - cd 


## Utopia

- cd c:\projects\utopia\utopia
- cmake -Ball_builds -DCMAKE_EXE_LINKER_FLAGS:STRING="/machine:x64" -DMPI_C_INCLUDE_PATH="C:\Program Files (x86)\Microsoft SDKs\MPI\Include" -DMPI_C_LIBRARIES="C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\msmpi.lib" -DMPI_CXX_LIBRARIES="C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\msmpi.lib" -DMPI_CXX_INCLUDE_PATH="C:\Program Files (x86)\Microsoft SDKs\MPI\Include" -DUTOPIA_ENABLE_TRACE_EXPR=ON -DUTOPIA_ENABLE_TRACE=ON -DUTOPIA_ENABLE_TRILINOS=ON -DUTOPIA_ENABLE_BLAS=ON -DUTOPIA_ENABLE_YAML_CPP=ON -DUTOPIA_ENABLE_POLYMORPHIC=ON -DUTOPIA_ENABLE_PETSC=ON -DUTOPIA_ENABLE_TESTS=ON -DUTOPIA_ENABLE_BENCHMARK=ON -DUTOPIA_ENABLE_EXAMPLES=ON -DUTOPIA_ENABLE_SCRIPTING=OFF -DUTOPIA_ENABLE_SLEPC=ON -DCMAKE_INSTALL_PREFIX=install -DUTOPIA_ENABLE_ISOLVER=ON -DUTOPIA_ENABLE_LOCAL_DEPENDENCIES_INSTALL=ON 

build_script:
  - cmake --build trilinos --config Release -j 4
  # - cmake --build all_builds --config Release -j 4
  # - ls -lah all_builds
  # - ls -lah all_builds/Release
  # - cmake --build all_builds --config Release --target install



