version: '{build}'
clone_folder: c:\projects\utopia

image: Visual Studio 2019

init:
  - ps: ($env:APPVEYOR_SAVE_CACHE_ON_ERROR = "true")


# cache dependencies libraries.
cache:



install:
# Install MS-MPI
- ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe'
- msmpisetup.exe -unattend
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%

# Install MS-MPI SDK
- ps: Start-FileDownload 'https://github.com/microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi'
- msmpisdk.msi /quiet /passive
- set PATH=C:\Program Files\Microsoft MPI\Bin;%PATH%


- cd c:\projects
- mkdir blas && cd blas
# Blas
- ps: Start-FileDownload 'https://icl.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/libblas.dll'
- ps: Start-FileDownload 'https://icl.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win32/libblas.lib'


- cd c:\projects
- mkdir lapack && cd lapack
# Lapack
- ps: Start-FileDownload 'https://icl.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.dll'
- ps: Start-FileDownload 'https://icl.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win32/liblapack.lib'


#Install Petsc
# Does not natively compile with windows
# Cannot use MS-MPI, Intel-MPI, MPICH2
# Options are, Cygwin to compile, MSYS, 
# - ps: Start-FileDownload 'https://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.18.3.tar.gz'
# - 7z x petsc-3.18.3.tar.gz -so | 7z x -si -ttar > nul
# - cd 


## Utopia
- cd c:\projects\utopia\utopia
- cmake -Ball_builds

build_script:
  - cmake --build all_builds -j 4 --target petsc
  - cmake --build all_builds -j 4 --target trilinos
  # - ls -lah all_builds
  # - ls -lah all_builds/Release
  # - cmake --build all_builds --config Release --target install



