image: zulianp/utopia-env:latest

pipelines:
  default:
    - step:
        script:
          - echo '======== Utopia with basic petsc/slepc backends ========='
          - apk add --no-cache curl build-base clang cmake git gfortran linux-headers 
          - cd utopia
          - mkdir build
          - mkdir bin
          - cd bin
          - cmake .. -DCMAKE_INSTALL_PREFIX=../build -DCMAKE_BUILD_TYPE=Debug
          - make
          - ./utopia_exec -verbose -bench