# Enabled
set(UTOPIA_ENABLE_MPI ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRILINOS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_BLAS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRACE_EXPR ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_CXX14_FEATURES ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TINY_EXPR ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_YAML_CPP ON CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_YAML_CPP ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_METIS ON CACHE BOOL "" FORCE)

# Temporary for utopia_fe.
set(UTOPIA_ENABLE_DEPRECATED_API OFF CACHE BOOL "" FORCE)
#

set(UTOPIA_BUILD_DOCUMENTATION ON CACHE BOOL "")

# Fix and enable
set(UTOPIA_REMOVE_TRILINOS_DEPRECATED_CODE OFF CACHE BOOL "" FORCE)
set(UTOPIA_PULL_REQUEST_MODE OFF CACHE BOOL "" FORCE)

if(NOT UTOPIA_ENABLE_PETSC)
    set(UTOPIA_ENABLE_PETSC
        ON
        CACHE STRING "Enable PETSC functionalities." FORCE)

    message(STATUS "[Status] UTOPIA_ENABLE_PETSC=OFF")
endif(NOT UTOPIA_ENABLE_PETSC)

set(UTOPIA_ENABLE_EIGER ON CACHE BOOL "" FORCE)
