# Enabled
set(UTOPIA_ENABLE_MPI ON)
set(UTOPIA_ENABLE_PETSC ON)
set(UTOPIA_ENABLE_TRILINOS ON)
set(UTOPIA_ENABLE_BLAS ON)
set(UTOPIA_ENABLE_YAML_CPP ON)
set(UTOPIA_INSTALL_PETSC ON)
set(UTOPIA_INSTALL_TRILINOS ON)
set(UTOPIA_INSTALL_SLEPC ON)
set(UTOPIA_INSTALL_YAML_CPP ON)


#Disabled

