# Enabled
set(UTOPIA_ENABLE_MPI ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_PETSC ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRILINOS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_BLAS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_YAML_CPP ON CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_PETSC ON CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_TRILINOS ON CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_SLEPC ON CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_YAML_CPP ON CACHE BOOL "" FORCE)


#Disabled

