# Enabled
set(UTOPIA_ENABLE_MPI ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_PETSC ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRILINOS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_BLAS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRACE_EXPR ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_CXX14_FEATURES ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TINY_EXPR ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_YAML_CPP ON CACHE BOOL "" FORCE)

# Temporary for utopia_fe.
set(UTOPIA_ENABLE_DEPRECATED_API ON CACHE BOOL "" FORCE)
#

set(UTOPIA_BUILD_DOCUMENTATION ON CACHE BOOL "")

# Fix and enable
set(UTOPIA_REMOVE_TRILINOS_DEPRECATED_CODE ON CACHE BOOL "" FORCE)
set(UTOPIA_PULL_REQUEST_MODE OFF CACHE BOOL "" FORCE)

if(UTOPIA_ENABLE_PARMETIS)
    set(UTOPIA_ENABLE_METIS
        ON
        CACHE STRING "Enable METIS functionalities." FORCE)
endif()

if(NOT UTOPIA_ENABLE_METIS)
    set(UTOPIA_ENABLE_METIS
        OFF
        CACHE STRING "Enable METIS functionalities." FORCE)

    message(STATUS "[Status] UTOPIA_ENABLE_METIS=OFF")
endif(NOT UTOPIA_ENABLE_METIS)

if(NOT UTOPIA_ENABLE_PARMETIS)
    set(UTOPIA_ENABLE_PARMETIS
        OFF
        CACHE STRING "Enable ParMETIS functionalities." FORCE)

    message(STATUS "[Status] UTOPIA_ENABLE_PARMETIS=OFF")
endif(NOT UTOPIA_ENABLE_PARMETIS)

# Disabled
set(UTOPIA_ENABLE_VC OFF CACHE BOOL "" FORCE)
set(UTOPIA_STATIC_DEPENDENCIES_ONLY OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_SLEPC OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRACE_EXPR OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_NO_ALLOC_REGIONS OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_SANITIZER OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_CLANG_TIDY OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_PETSC_DM_PLEX OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_EIGEN_3 OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_SCRIPTING OFF CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_TRILINOS OFF CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_PETSC OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_GPERFTOOLS OFF CACHE BOOL "" FORCE)
set(UTOPIA_SPACK_MODE OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
