# Enabled
set(UTOPIA_ENABLE_MPI ON)
set(UTOPIA_ENABLE_PETSC ON)
set(UTOPIA_ENABLE_TRILINOS ON)
set(UTOPIA_ENABLE_BLAS ON)
set(UTOPIA_ENABLE_TRACE ON)
set(UTOPIA_ENABLE_CXX14_FEATURES ON)
set(UTOPIA_ENABLE_TINY_EXPR ON)
set(UTOPIA_ENABLE_YAML_CPP ON)

set(UTOPIA_BUILD_DOCUMENTATION ON)

# Fix and enable
set(UTOPIA_REMOVE_TRILINOS_DEPRECATED_CODE ON)
set(UTOPIA_PULL_REQUEST_MODE OFF)

if(NOT UTOPIA_ENABLE_METIS)
    set(UTOPIA_ENABLE_METIS
        OFF
        CACHE STRING "Enable METIS functionalities." FORCE)

    message(STATUS "[Status] UTOPIA_ENABLE_METIS=OFF")
endif(NOT UTOPIA_ENABLE_METIS)

if(NOT UTOPIA_ENABLE_PARMETIS)
    set(UTOPIA_ENABLE_PARMETIS
        OFF
        CACHE STRING "Enable ParMETIS functionalities." FORCE)

    message(STATUS "[Status] UTOPIA_ENABLE_PARMETIS=OFF")
endif(NOT UTOPIA_ENABLE_PARMETIS)

# Disabled
set(UTOPIA_ENABLE_VC OFF)
set(UTOPIA_STATIC_DEPENDENCIES_ONLY OFF)
set(UTOPIA_ENABLE_SLEPC OFF)
set(UTOPIA_ENABLE_PARMETIS OFF)
set(UTOPIA_ENABLE_M3ELINSOL OFF)
set(UTOPIA_ENABLE_TRACE_EXPR OFF)
set(UTOPIA_ENABLE_NO_ALLOC_REGIONS OFF)
set(UTOPIA_ENABLE_SANITIZER OFF)
set(UTOPIA_ENABLE_DEPRECATED_API OFF)
set(UTOPIA_ENABLE_CLANG_TIDY OFF)
set(UTOPIA_ENABLE_PETSC_DM_PLEX OFF)
set(UTOPIA_ENABLE_EIGEN_3 OFF)
set(UTOPIA_ENABLE_SCRIPTING OFF)
set(UTOPIA_INSTALL_TRILINOS OFF)
set(UTOPIA_INSTALL_PETSC OFF)
set(UTOPIA_INSTALL_PETSC_DEBUG OFF)
set(UTOPIA_ENABLE_GPERFTOOLS OFF)
set(UTOPIA_SPACK_MODE OFF)
set(BUILD_SHARED_LIBS OFF)
