find_path(M3ELINSOL_INCLUDES 
	NAMES "M3Elinsol_CXX.hpp" "M3Elinsol.hpp"
	HINTS ../external/M3Elinsol
		  ${M3ELINSOL_DIR}
		  $ENV{M3ELINSOL_DIR}
	PATH_SUFFIXES include
	DOC "The M3ELINSOL_INCLUDES path"
)	

find_library(M3ELINSOL_LIBRARIES
	NAMES M3E_LINSOL
	PATHS ${M3ELINSOL_INCLUDES}/..
		  ${M3ELINSOL_DIR}
		  $ENV{M3ELINSOL_DIR}
    PATH_SUFFIXES lib
	DOC "The M3ELINSOL_LIBRARIES library to link against"
) 

# message(STATUS "M3ELINSOL: ${M3ELINSOL_INCLUDES}, ${M3ELINSOL_LIBRARIES}")

if(M3ELINSOL_INCLUDES AND M3ELINSOL_LIBRARIES)
	set(M3ELINSOL_FOUND TRUE)
endif()
