find_path(M3ELINSOL_INCLUDES 
	NAMES "M3Elinsol_CXX.hpp" "M3Elinsol.hpp"
	HINTS ../external/M3Elinsol
		  ${M3ELINSOL_DIR}
		  $ENV{M3ELINSOL_DIR}
	PATH_SUFFIXES include
	DOC "The M3ELINSOL_INCLUDES path"
)	

find_library(M3ELINSOL_LIBRARIES
	NAMES M3E_LINSOL
	PATHS ${M3ELINSOL_INCLUDES}/..
		  ${M3ELINSOL_DIR}
		  $ENV{M3ELINSOL_DIR}
    PATH_SUFFIXES lib
	DOC "The M3ELINSOL_LIBRARIES library to link against"
) 


find_path(M3ELINSOL_SRC 
	NAMES "M3Elinsol_CXX.cpp"
	HINTS ../external/M3Elinsol
		  ${M3ELINSOL_INCLUDES}/..
		  ${M3ELINSOL_DIR}
		  $ENV{M3ELINSOL_DIR}
	PATH_SUFFIXES src
	DOC "The M3ELINSOL_SRC path"
)	


list(APPEND 
	M3ELINSOL_SOURCE_FILES 
	"${M3ELINSOL_SRC}/M3Elinsol_CXX.cpp")

# message(STATUS "M3ELINSOL: ${M3ELINSOL_INCLUDES}, ${M3ELINSOL_LIBRARIES}, ${M3ELINSOL_SRC}")

if(M3ELINSOL_INCLUDES AND M3ELINSOL_LIBRARIES AND M3ELINSOL_SRC)
	set(M3ELINSOL_FOUND TRUE)
endif()
