export PETSC_INCLUDE_CONF=$PETSC_DIR/include

cd ../bin && cmake .. -DCMAKE_INSTALL_PREFIX=/users/becsekba/AVFLOW/moonolith/utopia/build -DPETSC_INCLUDES=$PETSC_DIR/include -DPETSC_INCLUDE_CONF=$PETSC_INCLUDE_CONF -DPETSC_LIBRARIES=$PETSC_DIR/lib/libcraypetsc_gnu_real.so -DPETSC_LIBRARY_SINGLE=$PETSC_DIR/lib/libcraypetsc_gnu_real.so -DPETSC_EXECUTABLE_RUNS=ON -DPETSC_COMPILER=cc -DWITH_PETSC_CRAY=ON -DMPI_CXX_COMPILER=CC -DUTOPIA_ARCHIVE_ONLY=ON && make -j4
cd ../scripts
