# Install script for directory: /shared/utopia/core

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE FILE FILES
    "/shared/utopia/core/./utopia_Allocations.hpp"
    "/shared/utopia/core/./utopia_Assert.hpp"
    "/shared/utopia/core/./utopia_BackendInfo.hpp"
    "/shared/utopia/core/./utopia_Castable.hpp"
    "/shared/utopia/core/./utopia_Clonable.hpp"
    "/shared/utopia/core/./utopia_Core.hpp"
    "/shared/utopia/core/./utopia_CoreDecprecatedHeaders.hpp"
    "/shared/utopia/core/./utopia_CppMacros.hpp"
    "/shared/utopia/core/./utopia_Device.hpp"
    "/shared/utopia/core/./utopia_DeviceView.hpp"
    "/shared/utopia/core/./utopia_Each.hpp"
    "/shared/utopia/core/./utopia_ElementWisePseudoInverse.hpp"
    "/shared/utopia/core/./utopia_ExprInliner.hpp"
    "/shared/utopia/core/./utopia_Factory.hpp"
    "/shared/utopia/core/./utopia_FactoryMethod.hpp"
    "/shared/utopia/core/./utopia_FillTypeQuery.hpp"
    "/shared/utopia/core/./utopia_For.hpp"
    "/shared/utopia/core/./utopia_ForwardDeclarations.hpp"
    "/shared/utopia/core/./utopia_IsSubTree.hpp"
    "/shared/utopia/core/./utopia_Library.hpp"
    "/shared/utopia/core/./utopia_Macros.hpp"
    "/shared/utopia/core/./utopia_MatChop.hpp"
    "/shared/utopia/core/./utopia_MaxRowNNZ.hpp"
    "/shared/utopia/core/./utopia_Monitoring.hpp"
    "/shared/utopia/core/./utopia_NormalizeRows.hpp"
    "/shared/utopia/core/./utopia_ParallelEach.hpp"
    "/shared/utopia/core/./utopia_RangeDevice.hpp"
    "/shared/utopia/core/./utopia_Recorder.hpp"
    "/shared/utopia/core/./utopia_Reduction.hpp"
    "/shared/utopia/core/./utopia_Rename.hpp"
    "/shared/utopia/core/./utopia_RowView.hpp"
    "/shared/utopia/core/./utopia_ScalarCast.hpp"
    "/shared/utopia/core/./utopia_StaticMath.hpp"
    "/shared/utopia/core/./utopia_StoreAs.hpp"
    "/shared/utopia/core/./utopia_Temp.hpp"
    "/shared/utopia/core/./utopia_TensorProductWithIdentity.hpp"
    "/shared/utopia/core/./utopia_Tracer.hpp"
    "/shared/utopia/core/./utopia_Traits.hpp"
    "/shared/utopia/core/./utopia_TreeNavigator.hpp"
    "/shared/utopia/core/./utopia_TreeProperties.hpp"
    "/shared/utopia/core/./utopia_Unfold.hpp"
    "/shared/utopia/core/./utopia_Variable.hpp"
    "/shared/utopia/core/./utopia_Wrapper.hpp"
    "/shared/utopia/core/./utopia_ZeroRowsToIdentity.hpp"
    "/shared/utopia/core/eval/utopia_Eval.hpp"
    "/shared/utopia/core/eval/utopia_Eval_AXPY.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Assign.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Binary.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Blocks.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Construct.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Determinant.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Diag.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Differentiable.hpp"
    "/shared/utopia/core/eval/utopia_Eval_DotOpDot.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Empty.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Factory.hpp"
    "/shared/utopia/core/eval/utopia_Eval_InPlace.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Inverse.hpp"
    "/shared/utopia/core/eval/utopia_Eval_KroneckerProduct.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Multiply.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Negate.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Number.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Reduce.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Residual.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Select.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Structure.hpp"
    "/shared/utopia/core/eval/utopia_Eval_TensorReduce.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Ternary.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Transpose.hpp"
    "/shared/utopia/core/eval/utopia_Eval_Unary.hpp"
    "/shared/utopia/core/eval/utopia_Eval_View.hpp"
    "/shared/utopia/core/eval/utopia_MultiReduce.hpp"
    "/shared/utopia/core/expressions/utopia_Assign.hpp"
    "/shared/utopia/core/expressions/utopia_AuxiliaryExpressions.hpp"
    "/shared/utopia/core/expressions/utopia_Binary.hpp"
    "/shared/utopia/core/expressions/utopia_Blocks.hpp"
    "/shared/utopia/core/expressions/utopia_Boolean.hpp"
    "/shared/utopia/core/expressions/utopia_Collection.hpp"
    "/shared/utopia/core/expressions/utopia_Cond.hpp"
    "/shared/utopia/core/expressions/utopia_ConvertTensor.hpp"
    "/shared/utopia/core/expressions/utopia_Determinant.hpp"
    "/shared/utopia/core/expressions/utopia_Diag.hpp"
    "/shared/utopia/core/expressions/utopia_DiffController.hpp"
    "/shared/utopia/core/expressions/utopia_DotVecVecs.hpp"
    "/shared/utopia/core/expressions/utopia_Equality.hpp"
    "/shared/utopia/core/expressions/utopia_Expression.hpp"
    "/shared/utopia/core/expressions/utopia_Expressions.hpp"
    "/shared/utopia/core/expressions/utopia_FiniteDifference.hpp"
    "/shared/utopia/core/expressions/utopia_InPlace.hpp"
    "/shared/utopia/core/expressions/utopia_Inverse.hpp"
    "/shared/utopia/core/expressions/utopia_Literal.hpp"
    "/shared/utopia/core/expressions/utopia_MatGetCol.hpp"
    "/shared/utopia/core/expressions/utopia_MatrixPtAPProduct.hpp"
    "/shared/utopia/core/expressions/utopia_Multiply.hpp"
    "/shared/utopia/core/expressions/utopia_Mutable.hpp"
    "/shared/utopia/core/expressions/utopia_Negate.hpp"
    "/shared/utopia/core/expressions/utopia_Norm.hpp"
    "/shared/utopia/core/expressions/utopia_Operations.hpp"
    "/shared/utopia/core/expressions/utopia_Operators.hpp"
    "/shared/utopia/core/expressions/utopia_Optional.hpp"
    "/shared/utopia/core/expressions/utopia_OuterProduct.hpp"
    "/shared/utopia/core/expressions/utopia_Range.hpp"
    "/shared/utopia/core/expressions/utopia_Ranged.hpp"
    "/shared/utopia/core/expressions/utopia_Readable.hpp"
    "/shared/utopia/core/expressions/utopia_Reduce.hpp"
    "/shared/utopia/core/expressions/utopia_Scalar.hpp"
    "/shared/utopia/core/expressions/utopia_Select.hpp"
    "/shared/utopia/core/expressions/utopia_Size.hpp"
    "/shared/utopia/core/expressions/utopia_Structure.hpp"
    "/shared/utopia/core/expressions/utopia_Structured.hpp"
    "/shared/utopia/core/expressions/utopia_TensorReduce.hpp"
    "/shared/utopia/core/expressions/utopia_Trace.hpp"
    "/shared/utopia/core/expressions/utopia_Transposed.hpp"
    "/shared/utopia/core/expressions/utopia_Unary.hpp"
    "/shared/utopia/core/expressions/utopia_View.hpp"
    "/shared/utopia/core/expressions/utopia_Writable.hpp"
    "/shared/utopia/core/expressions_parallel/utopia_ExpressionsParallel.hpp"
    "/shared/utopia/core/expressions_parallel/utopia_LocalDiagBlock.hpp"
    "/shared/utopia/core/expressions_parallel/utopia_LocalRedistribute.hpp"
    "/shared/utopia/core/interfaces/utopia_AbstractMatrix.hpp"
    "/shared/utopia/core/interfaces/utopia_AbstractVector.hpp"
    "/shared/utopia/core/interfaces/utopia_Array.hpp"
    "/shared/utopia/core/interfaces/utopia_BLAS_Operands.hpp"
    "/shared/utopia/core/interfaces/utopia_Communicator.hpp"
    "/shared/utopia/core/interfaces/utopia_Comparable.hpp"
    "/shared/utopia/core/interfaces/utopia_Constructible.hpp"
    "/shared/utopia/core/interfaces/utopia_DistributedObject.hpp"
    "/shared/utopia/core/interfaces/utopia_DynamicTypeDistributedMatrix.hpp"
    "/shared/utopia/core/interfaces/utopia_ElementWiseOperand.hpp"
    "/shared/utopia/core/interfaces/utopia_Enums.hpp"
    "/shared/utopia/core/interfaces/utopia_IndexSet.hpp"
    "/shared/utopia/core/interfaces/utopia_Interfaces.hpp"
    "/shared/utopia/core/interfaces/utopia_Layout.hpp"
    "/shared/utopia/core/interfaces/utopia_MPI_Operations.hpp"
    "/shared/utopia/core/interfaces/utopia_Matrix.hpp"
    "/shared/utopia/core/interfaces/utopia_Normed.hpp"
    "/shared/utopia/core/interfaces/utopia_Operator.hpp"
    "/shared/utopia/core/interfaces/utopia_Reducible.hpp"
    "/shared/utopia/core/interfaces/utopia_Tensor.hpp"
    "/shared/utopia/core/interfaces/utopia_Transformable.hpp"
    "/shared/utopia/core/interfaces/utopia_Vector.hpp"
    "/shared/utopia/core/view/utopia_Accessor.hpp"
    "/shared/utopia/core/view/utopia_Algorithms.hpp"
    "/shared/utopia/core/view/utopia_ArrayView.hpp"
    "/shared/utopia/core/view/utopia_ArrayView4.hpp"
    "/shared/utopia/core/view/utopia_DeviceNumber.hpp"
    "/shared/utopia/core/view/utopia_MatrixView.hpp"
    "/shared/utopia/core/view/utopia_TensorView.hpp"
    "/shared/utopia/core/view/utopia_TensorView4.hpp"
    "/shared/utopia/core/view/utopia_VectorView.hpp"
    "/shared/utopia/core/view/utopia_ViewForwardDeclarations.hpp"
    "/shared/utopia/core/view/utopia_ViewTraits.hpp"
    "/shared/utopia/core/view/utopia_Views.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceApproxEqual.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceAssign.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceBinary.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceCrossProduct.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceDeterminant.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceDiag.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceDot.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceEigenDecomposition.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceEigenDecompositionNew.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceEigenValues.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceEigenVectors.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceExpression.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceFind.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceIdentity.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceInPlace.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceInverse.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceMultiply.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceNorm.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceOp.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceOperations.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceOuterProduct.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceReduce.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceTensorContraction.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceTensorProduct.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceTensorReduce.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceTrace.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceTranspose.hpp"
    "/shared/utopia/core/view/expressions/utopia_DeviceUnary.hpp"
    "/shared/utopia/core/view/expressions/utopia_InlineEval.hpp"
    "/shared/utopia/core/console/utopia_IOStream.hpp"
    "/shared/utopia/core/console/utopia_Logger.hpp"
    "/shared/utopia/core/console/utopia_Reporter.hpp"
    )
endif()

