# Enabled 
set(UTOPIA_ENABLE_CXX14_FEATURES ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_INTREPID2 ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_NEW_TRANSFER ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_WARNINGS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_STK ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_MOONOLITH ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_SFEM ON CACHE BOOL "" FORCE)

# Disabled
set(UTOPIA_ENABLE_SANITIZER ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_BOOST OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_MOONOLITH_PROFILER OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_MOOSE_ENV_MODE OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRILINOS_ALGEBRA OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_MARS OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_MARS_VTK OFF CACHE BOOL "" FORCE)
# set(UTOPIA_ENABLE_MARS_ADIOS2 OFF CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_LIBMESH OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_LIBMESH OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_ARBORX OFF CACHE BOOL "" FORCE)


# message(FATAL_ERROR "TRILINOS_DIR=${TRILINOS_DIR}")