# Enabled 
set(UTOPIA_ENABLE_MARS ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_TRILINOS ON CACHE BOOL "" FORCE)


# Disabled
set(UTOPIA_ENABLE_LIBMESH OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_STK OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_PETSC_DM OFF CACHE BOOL "" FORCE)



set(CMAKE_CXX_COMPILER "$ENV{TRILINOS_DIR}/bin/nvcc_wrapper")