# Enabled 
set(UTOPIA_ENABLE_PETSC ON CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_PETSCDM OFF CACHE BOOL "" FORCE)
set(UTOPIA_ENABLE_LIBMESH ON CACHE BOOL "" FORCE)
set(UTOPIA_INSTALL_LIBMESH ON CACHE BOOL "" FORCE)


# Disabled