# Enabled 
set(UTOPIA_ENABLE_CXX14_FEATURES ON CACHE BOOL "")
set(UTOPIA_ENABLE_INTREPID2 ON CACHE BOOL "")
set(UTOPIA_ENABLE_NEW_TRANSFER ON CACHE BOOL "")
set(UTOPIA_ENABLE_WARNINGS ON CACHE BOOL "")
set(UTOPIA_ENABLE_STK ON CACHE BOOL "")
set(UTOPIA_ENABLE_MOONOLITH ON CACHE BOOL "")

# Disabled
set(UTOPIA_ENABLE_SANITIZER ON CACHE BOOL "")
set(UTOPIA_ENABLE_BOOST OFF CACHE BOOL "")
set(UTOPIA_ENABLE_MOONOLITH_PROFILER OFF CACHE BOOL "")
set(UTOPIA_ENABLE_MOOSE_ENV_MODE OFF CACHE BOOL "")
set(UTOPIA_ENABLE_TRILINOS_ALGEBRA OFF CACHE BOOL "")
set(UTOPIA_ENABLE_MARS OFF CACHE BOOL "")
set(UTOPIA_ENABLE_MARS_VTK OFF CACHE BOOL "")
# set(UTOPIA_ENABLE_MARS_ADIOS2 OFF CACHE BOOL "")
set(UTOPIA_INSTALL_LIBMESH OFF CACHE BOOL "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(UTOPIA_ENABLE_LIBMESH OFF CACHE BOOL "")
set(UTOPIA_ENABLE_ARBORX OFF CACHE BOOL "")


# message(FATAL_ERROR "TRILINOS_DIR=${TRILINOS_DIR}")