# Enabled 
set(UTOPIA_ENABLE_CXX14_FEATURES ON)
set(UTOPIA_ENABLE_INTREPID2 ON)
set(UTOPIA_ENABLE_NEW_TRANSFER ON)
set(UTOPIA_ENABLE_WARNINGS ON)
set(UTOPIA_ENABLE_STK ON)
set(UTOPIA_ENABLE_MOONOLITH ON)

# Disabled
set(UTOPIA_ENABLE_SANITIZER OFF)
set(UTOPIA_ENABLE_BOOST OFF)
set(UTOPIA_ENABLE_MOONOLITH_PROFILER OFF)
set(UTOPIA_ENABLE_MOOSE_ENV_MODE OFF)
set(UTOPIA_ENABLE_TRILINOS_ALGEBRA OFF)
set(UTOPIA_ENABLE_MARS OFF)
set(UTOPIA_ENABLE_MARS_VTK OFF)
set(UTOPIA_ENABLE_MARS_ADIOS2 OFF)
set(UTOPIA_INSTALL_LIBMESH OFF)
set(BUILD_SHARED_LIBS OFF)
set(UTOPIA_ENABLE_LIBMESH OFF)
set(UTOPIA_ENABLE_ARBORX OFF)


# message(FATAL_ERROR "TRILINOS_DIR=${TRILINOS_DIR}")