cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_PREFIX=$UTOPIA_DIR -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_FLAGS="-fopenmp $MARCH -Wall -std=c++11" \
     -DTRY_UTOPIA_WITH_PETSC=OFF \
     -DTRY_WITH_TRILINOS=ON -DTRILINOS_DIR=${TRILINOS_DIR}/lib/cmake/Trilinos \
     -DTRY_WITH_EIGEN_3=ON -DEIGEN3_INCLUDE_DIR=${EIGEN_DIR}/include/eigen3 \
     -DTRY_WITH_CUDA=OFF \
     -DUTOPIA_ARCHIVE_ONLY=OFF \
     ${SRCDIR}/utopia