
cmake_minimum_required(VERSION 3.13)

set(command "/usr/bin/cmake;-DCMAKE_CXX_STANDARD=14;-DCMAKE_INSTALL_PREFIX=/shared/utopia/../external/Trilinos;-DCMAKE_BUILD_TYPE=Release;-DUTOPIA_ENABLE_SANITIZER=OFF;-DCMAKE_CXX_COMPILER=/usr/bin/clang++;-DCMAKE_C_COMPILER=/usr/bin/clang;-DCMAKE_CXX_FLAGS_DEBUG=-g;-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG;-DTPL_ENABLE_MPI=ON;-DMPI_BASE_DIR=/opt/petsc;-DTrilinos_ENABLE_Tpetra=ON;-DTrilinos_ENABLE_TpetraCore=ON;-DTrilinos_ENABLE_Belos=ON;-DTrilinos_ENABLE_Amesos2=ON;-DTrilinos_ENABLE_Ifpack2=ON;-DTrilinos_ENABLE_MueLu=ON;-DTrilinos_ENABLE_NOX=ON ;-DAmesos2_ENABLE_EXPLICIT_INSTANTIATION=ON;-DIfpack2_ENABLE_EXPLICIT_INSTANTIATION=ON;-DKOKKOS_ENABLE_EXPLICIT_INSTANTIATION=ON;-DMueLu_ENABLE_EXPLICIT_INSTANTIATION=ON;-DRTOp_ENABLE_EXPLICIT_INSTANTIATION=ON;-DStratimikos_ENABLE_EXPLICIT_INSTANTIATION=ON;-DTeuchos_ENABLE_EXPLICIT_INSTANTIATION=ON;-DThyra_ENABLE_EXPLICIT_INSTANTIATION=ON;-DTpetraCore_ENABLE_EXPLICIT_INSTANTIATION=ON;-DTpetra_ENABLE_EXPLICIT_INSTANTIATION=ON;-DTrilinos_ENABLE_EXPLICIT_INSTANTIATION=ON;-DXpetra_ENABLE_EXPLICIT_INSTANTIATION=ON;-GUnix Makefiles;/shared/utopia/build_docker/stage/src/trilinos")
set(log_merged "")
set(log_output_on_failure "")
set(stdout_log "/shared/utopia/build_docker/stage/src/trilinos-stamp/trilinos-configure-out.log")
set(stderr_log "/shared/utopia/build_docker/stage/src/trilinos-stamp/trilinos-configure-err.log")
execute_process(
  COMMAND ${command}
  RESULT_VARIABLE result
  OUTPUT_FILE "${stdout_log}"
  ERROR_FILE "${stderr_log}"
  )
macro(read_up_to_max_size log_file output_var)
  file(SIZE ${log_file} determined_size)
  set(max_size 10240)
  if (determined_size GREATER max_size)
    math(EXPR seek_position "${determined_size} - ${max_size}")
    file(READ ${log_file} ${output_var} OFFSET ${seek_position})
    set(${output_var} "...skipping to end...\n${${output_var}}")
  else()
    file(READ ${log_file} ${output_var})
  endif()
endmacro()
if(result)
  set(msg "Command failed: ${result}\n")
  foreach(arg IN LISTS command)
    set(msg "${msg} '${arg}'")
  endforeach()
  if (${log_merged})
    set(msg "${msg}\nSee also\n  ${stderr_log}")
  else()
    set(msg "${msg}\nSee also\n  /shared/utopia/build_docker/stage/src/trilinos-stamp/trilinos-configure-*.log")
  endif()
  if (${log_output_on_failure})
    message(SEND_ERROR "${msg}")
    if (${log_merged})
      read_up_to_max_size("${stderr_log}" error_log_contents)
      message(STATUS "Log output is:\n${error_log_contents}")
    else()
      read_up_to_max_size("${stdout_log}" out_log_contents)
      read_up_to_max_size("${stderr_log}" err_log_contents)
      message(STATUS "stdout output is:\n${out_log_contents}")
      message(STATUS "stderr output is:\n${err_log_contents}")
    endif()
    message(FATAL_ERROR "Stopping after outputting logs.")
  else()
    message(FATAL_ERROR "${msg}")
  endif()
else()
  set(msg "trilinos configure command succeeded.  See also /shared/utopia/build_docker/stage/src/trilinos-stamp/trilinos-configure-*.log")
  message(STATUS "${msg}")
endif()
