#ifndef UTOPIA_LIBMESH_CONTEXT_HPP
#define UTOPIA_LIBMESH_CONTEXT_HPP

#include "libmesh/mesh.h"
#include "libmesh/equation_systems.h"

#include <memory>

namespace utopia {

	template<class SystemType>
	class LibMeshFEContext {
	public:
		LibMeshFEContext(const std::shared_ptr<libMesh::MeshBase> &mesh)
		: mesh(mesh),
		equation_systems(*mesh), 
		system(equation_systems.add_system<SystemType> ("AutoGenerated")) 
		{}

		std::shared_ptr<libMesh::MeshBase> mesh;
		libMesh::EquationSystems equation_systems;
		SystemType & system;
	};
}

#endif //UTOPIA_LIBMESH_CONTEXT_HPP
